layout_spectrum: 0.7030075
color:
  saturation: 0.5998926
  brandStrength: 0.7781955
  lightness: 0
  brandColors:
    - '#ACAAA3'
    - '#201F1F'
    - '#DEE2E8'
    - '#534C41'
    - '#FF9139'
  rhythmicContrast: 0.2566978
typography_spectrum: 0.4581096
name: Rick Nohl Media
